### ISSUE TITLE
Provision and Validate functions not being called in the Example module

### ISSUE THREAD

**Issue by mseankelly-Kin** [gotenberg/gotenberg-template-repository#1]
I'm looking into creating a custom module. As a first step, I thought I'd get the `example` module running and play around with it. I put log statements in the `init`, `Descriptor`, `Provision`, and `Validate` methods to see when they get called. It appears to me that `Provision` and `Validate` are never being called. Is that expected? If not, thoughts on how to fix it?

Here's the `example.go` file with the log statements:

``` golang
package example

import (
	"fmt"
	"log"

	"github.com/gotenberg/gotenberg/v7/pkg/gotenberg"
	flag "github.com/spf13/pflag"
	"go.uber.org/multierr"
)

func init() {
	log.Print("Running example.init()")

	gotenberg.MustRegisterModule(Example{})
}

// Example is our module. It does nothing.
type Example struct {
	strProp string
	intProp int
}

// Descriptor returns an Example's module descriptor.
func (mod Example) Descriptor() gotenberg.ModuleDescriptor {
	log.Print("Running example.Descriptor()")
	return gotenberg.ModuleDescriptor{
		ID: "example",
		FlagSet: func() *flag.FlagSet {
			fs := flag.NewFlagSet("example", flag.ExitOnError)
			// fs.String("example-str-prop", "", "Set the string property")
			// fs.Int("example-int-prop", 0, "Set the int property")

			return fs
		}(),
		New: func() gotenberg.Module { return new(Example) },
	}
}

// Provision sets the module properties.
func (mod *Example) Provision(ctx *gotenberg.Context) error {
	log.Print("Running example.Provision()")
	flags := ctx.ParsedFlags()
	mod.strProp = flags.MustString("example-str-prop")
	mod.intProp = flags.MustInt("example-int-prop")

	return nil
}

// Validate validates the module properties.
func (mod Example) Validate() error {
	log.Print("Running example.Validate()")
	var err error

	if mod.strProp == "bar" {
		err = multierr.Append(err, fmt.Errorf("str prop must be different than bar"))
	}

	if mod.intProp == 1337 {
		err = multierr.Append(err, fmt.Errorf("int prop must be different than 1337"))
	}

	return err
}

// Interface guards.
var (
	_ gotenberg.Module      = (*Example)(nil)
	_ gotenberg.Provisioner = (*Example)(nil)
	_ gotenberg.Validator   = (*Example)(nil)
)
```

This is what I get in the console:

```
> docker run --rm -p 3000:3000 app/gotenberg:7-app-snapshot
2023/04/16 20:19:58 Running ddconfig.init()
2023/04/16 20:19:58 Running ddconfig.Descriptor()

  _____     __           __               
 / ___/__  / /____ ___  / /  ___ _______ _
/ (_ / _ \/ __/ -_) _ \/ _ \/ -_) __/ _ '/
\___/\___/\__/\__/_//_/_.__/\__/_/  \_, / 
                                   /___/

A Docker-powered stateless API for PDF files.
Version: 7-app-snapshot
-------------------------------------------------------
[SYSTEM] modules: api chromium example gc libreoffice logging pdfcpu pdfengines pdftk prometheus qpdf uno uno-pdfengine webhook 
[SYSTEM] pdfengines: pdfcpu pdftk qpdf uno-pdfengine
[SYSTEM] gc: application started
[SYSTEM] prometheus: collecting metrics
[SYSTEM] uno: long-running LibreOffice listener ready to start
[SYSTEM] api: server listening on port 3000
```

**Comment by mseankelly-Kin** [comment]
I'm guessing that we're not getting to to this `loadModule` call on the `Context`: https://github.com/gotenberg/gotenberg/blob/77c6e541d6f8953b3f29b875f2a96707d0781e13/pkg/gotenberg/context.go#L90

**Comment by gulien** [comment]
Hello @mseankelly-Kin!

That's weird 🤔 out of curiosity, are the flags available? Does the validation works if you use a wrong value?

In any case, it seems that your module is correctly loaded:

> [SYSTEM] modules: api chromium **example** gc libreoffice logging pdfcpu pdfengines pdftk prometheus qpdf uno uno-pdfengine webhook

But with these commented:

```go
// fs.String("example-str-prop", "", "Set the string property")
// fs.Int("example-int-prop", 0, "Set the int property")
```
It should throw an error while provisionning.

**Comment by gulien** [comment]
Ok I confirm it does not work:

![Capture d’écran 2023-04-17 à 10 31 26](https://user-images.githubusercontent.com/8983173/232429744-87adf9d7-b267-40f7-bfb6-5d9b5203bbf9.png)

**Comment by gulien** [comment]
Alright, I get it 😄 it actually works as expected.

The `example` module is not used by anything, and therefore not loaded (only registered):

1. It's not an `App`..
2. It's not a `SystemLogger`.
3. It's not registered within other modules (see https://github.com/gotenberg/gotenberg/blob/main/pkg/modules/pdfengines/pdfengines.go#L68).

I added the `SystemLogger` interface to it (https://github.com/gotenberg/gotenberg-template-repository/blob/main/pkg/modules/example/example.go#L60) so that it may now be loaded as a standalone.
